spring:
  application:
    name: db-backend
  datasource:
    url: url
    username: username
    password: password
server:
  port: 8081

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.springframework.jdbc.core: TRACE
    org.springframework.jdbc.datasource: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE

