spring:
  application:
    name: db-backend
  datasource:
    url: ${DB_DATASOURCE_URL}
    username: ${DB_DATASOURCE_USERNAME}
    password: ${DB_DATASOURCE_PASSWORD}
server:
  port: 8084

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.springframework.jdbc.core: TRACE
    org.springframework.jdbc.datasource: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.security: TRACE
